### ISSUE TITLE
Installing it with the current npm version (9.6.7) does not generate an executable

### ISSUE THREAD

**Issue by hnorkowski** [sititou70/kbuild-progress-npm#4]
When installing with `npm install -g kbuild-progress` there are no errors shown however no binary or *.js is generated

**Comment by sititou70** [comment]
The package.json has been modified to support the latest npm.

However, there is a successor tool that works with a more efficient algorithm. (I forgot to mention this in the README. Sorry.)

See below if you like:

https://github.com/sititou70/kbuild-progress

**Comment by hnorkowski** [comment]
Alright, thanks for the info! I will close this.
